
version: '3.9'

#####
# Common Configs
####

#x-healthcheck:
#  healthcheck:
#    test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
#    interval: 1m30s
#    timeout: 10s
#    retries: 3
#    start_period: 40s


#####
# project name
#####
name: media_server

#####
# services section
#####
services:

  ###
  # Portainer - Manage docker contsainers and stack
  ###
  portainer:
    image: portainer/portainer-ce:linux-arm64
    container_name: portainer
    hostname: $HOSTNAME
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
    networks:
      - media_net
    ports:
      - "9000:9000"
      - "9443:9443"
      - "8000:8000"
    volumes:
      - "/var/lib/docker:/var/lib/docker"
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #healthcheck:
    #  test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:9000/api/system/#status || exit 1"
    #  interval: 60s
    #  retries: 3
    #  start_period: 90s
    #  timeout: 10s
    #labels:
    #  - "autoheal=true"
    
  ###
  # Dashy alternative to heimdall port 4000
  ###
  dashy:
    # build: .
    image: lissy93/dashy
    container_name: dashy
    hostname: $HOSTNAME
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
      DASHY_CONFIG: "/app/public/conf.yml"
      HOSTNAME: "${HOSTNAME:-example.com}"
      HOST_IP:  "${MEDIA_SERVER_IP}"
      DOMAIN:   "${DOMAIN}"
      TAUTULLI_GITHUB_AUTH: ${TAUTULLI_GITHUB_AUTH}
    networks:
      - media_net
    ports:
      - 4000:80
    volumes:
      - ./apps/dashy/config/conf.yml:/app/public/conf.yml
      - ./apps/dashy/icons:/app/public/icons
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 15m
      timeout: 10s
      retries: 3
      start_period: 40s  

  ###
  # Plex- Media Server
  ###  
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: $HOSTNAME
    environment:
      PLEX_UID: "${PUID:-1000}"
      PLEX_GID: "${PGID:-1000}"
      TZ:       "${TZ:-Etc/UTC}"
      VERSION:  "${PLEX_VERSION:-docker}"
      PLEX_CLAIM_FILE:   "/run/secrets/plex_claim"
      PLEX_ADVERTISE_IP: "${MEDIA_SERVER_IP}:32400"
    secrets:
      - plex_claim
    networks:
      - media_net
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - "./media/disc1/media/Movies:/movies"
      - "./media/disc1/media/tv:/tv"
      - "/var/lib/docker:/var/lib/docker"
      - "plex_data:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #healthcheck:
    #  test: curl --fail http://${MEDIA_SERVER_IP}:32400/web || exit 1
    #  interval: 60s
    #  retries: 5
    #  start_period: 50s
    #  timeout: 10s
    #labels:
    #  - "autoheal=true"
  
  ###
  #  tautulli - Utilities for Plex
  ###
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: $HOSTNAME
    depends_on:
      plex:
        condition: service_started
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
      GUID: "${GUID:-1000}"
      TAUTULLI_GITHUB_AUTH_FILE: /run/secrets/tautulli_github_auth
    secrets:
      - tautulli_github_auth
    networks:
      - media_net
    ports:
      - "8181:8181"
    volumes:
      - "./apps/tautulli/config:/config"
      - "./apps/plex/logs:/plexlogs"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #healthcheck:
    #  test: curl --fail http://localhost || exit 1
    #  interval: 55s
    #  retries: 5
    ##  start_period: 50s
     # timeout: 10s
    #labels:
    #  - "autoheal=true"

  ###
  # Airsonic advanced port 4040
  ###
  airsonic:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
    networks:
      - media_net
    ports:
      - 4040:4040
    volumes:
      - "./media/disc1/media/audio/music:/music"
      - "./media/disc1/media/audio/playlists:/playlists"
      - "./media/disc1/media/audio/podcasts:/podcasts"
      - "./apps/airsonic/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
#    healthcheck:
#      test: "wget --no-verbose --tries=3 --spider http://127.0.0.1:4040 || exit 1"
#      interval: 75s
#      retries: 5
#      start_period: 60s
#    labels:
#      - "autoheal=true"

  ###
  # music tagging app
  ###
  #picard:
  #  image: mikenye/picard:latest
  #  container_name: picard
  #  environment:
  #    PUID: "${PUID:-1000}"
  #    PGID: "${PGID:-1000}"
  #    TZ:   "${TZ:-Etc/UTC}"
  #  networks:
  #    - "media_net"
  #  ports:
  #    - "5800:5800"
  #  volumes:
  #    - "./apps/picard:/config:rw"
  #    - "./media/disc1/media/audio/music/:/storage:rw"
  #  security_opt:
  #    - no-new-privileges:true
  #  restart: unless-stopped 
  
  ###
  # syncthing to sync files between devices
  ###
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
    networks:
      - media_net
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - "./apps/syncthing/config:/config"
      - "./apps/syncthing/data:/data1"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped 
    #healthcheck:
    #  test: curl --fail http://localhost || exit 1
    #  interval: 60s
    #  retries: 5
    #  start_period: 65s
    #  timeout: 10s
    #labels:
    #  - "autoukheal=true"  

  ###
  # gluetun - vpn and kill switch
  ###cccccbhikhbkigk
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER:-nordvpn}"
      VPN_TYPE: "${VPN_TYPE:-openvpn}" # openvpn or wireguard
      OPENVPN_USER: "$OPENVPN_USER"
      OPENVPN_PASSWORD: "$OPENVPN_PASSWORD"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
    # QUERY: 'filters\[servers_groups\]\[identifier\]=legacy_p2p'
    #VPN_PASSWORD: $NVPN_PASSWORD
    #NVPN_PASSWORD: $NVPN_PASSWORD
      SERVER_REGIONS: "US West,US East,Canada"
      UPDATER_PERIOD: "12h"
    #WIREGUARD_PRIVATE_KEY: "$NVPN_WIREGUARD_PRIVATE_KEY"
    networks:
      - media_net
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "6999:6999"
      - "$WEBUI_PORT:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./apps/gluetun/config:/gluetun"
      - "/lib/modules:/lib/modules:ro"
    devices:
      - "/dev/net/tun"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  ###
  # dozzle log aggregator
  ###
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
      DOZZLE_LEVEL: "trace"
    networks:
      - media_net
    ports:
      - "8282:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: unless-stopped
    
    #healthcheck:
    #  test: ["CMD", "/dozzle", "healthcheck"]
    #  interval: 5m
    #  timeout: 15s
    #  retries: 3
    #  start_period: 60s
    #labels:
    #  - "autoheal=true"
  ###
  # Watchtower to automate updates
  ###
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: $HOSTNAME
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "3600"
    networks:
      - media_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: unless-stopped
  
  ###
  # Prometheus and Grafana for monitoring
  ###
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "nobody"
    depends_on:
      - cadvisor
      - node-exporter
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
    networks:
      - media_net
    ports:
      - "9090:9090"
    volumes:
      - "./apps/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./apps/prometheus/data:/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'  
    restart: unless-stopped
  
  ###
  # Node Exporter and cAdvisor for monitoring
  ###
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    pid: host
    networks:
      - media_net
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro" 
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    restart: unless-stopped
    #healthcheck:
    #  test: "curl --fail http://localhost:9100/metrics || exit 1"
    #  
    # interval: 60s
    #  retries: 5

    #  start_period: 20s
    #  timeout: 10s

  ###
  # cAdvisor for monitoring
  ###
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1 
    container_name: cadvisor
    privileged: true
    networks:
      - media_net
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/etc/machine-id:/etc/machine-id"
      - "/dev/disk/:/dev/disk:ro"
      - "./apps/cadvisor/logs:/var/log/cadvisor"
    devices:
      - /dev/kmsg:/dev/kmsg
    command:
      - '--docker_only=true'
      - '--housekeeping_interval=33s'
      - '--disable_metrics=disk,tcp,udp,percpu,sched,process,referenced_memory,cpu_topology'
      - '--log_dir="/var/log/cadvisor"'
    #other values: filesystem,cpu,precpu,load,uptime,vmstat,meminfo,netstat,perf,net,cpu,
    restart: unless-stopped
      
  ###
  # Grafana for monitoring
  ###
  grafana:
    image: grafana/grafana:latest
    user: ":"
    container_name: grafana
    depends_on:
      - prometheus
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ:   ${TZ:-Etc/UTC}
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    networks:
      - media_net
    ports:      
      - 3000:3000
    volumes:
      - ./apps/grafana/config:/var/lib/grafana
      - ./apps/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    #healthcheck:
    #  test: GET /api/health Accept application.json --fail || exit 1 #curl --fail http://localhost || exit 1
    #  interval: 60s
    #  retries: 5
    #  start_period: 20s
    #  timeout: 10s
    # labels:
    #  - "autoheal=true"
  ###
  # Autoheal to restart containers
  ###
  autoheal:
    #build: autoheal
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    tty: true
    environment:
      COMPOSE_PROJECT_NAME: $HOSTNAME
      AUTOHEAL_INTERVAL: "${AUTOHEAL_INTERVAL:-60)}"
      AUTOHEAL_START_PERIOD: "${AUTOHEAL_START_PERIOD:-300}"
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: "${AUTOHEAL_DEFAULT_STOP_TIMEOUT:-10}"
      AUTOHEAL_CONTAINER_LABEL: "${AUTOHEAL_CONTAINER_LABEL:-true}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ:   "${TZ:-Etc/UTC}"
    network_mode: none
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "no"

#####
# Volumes section  
#####
volumes:
  portainer_data:
    external: true
  plex_data:
    external: true

####
# Networks 
###
networks:
  media_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1

#####
# Secrets
#####
secrets:
  plex_claim:
    file: ./run/secrets.d/plex_claim.txt
  cf_api_email:
    file: ./run/secrets.d/cf_api_email.txt
  cf_dns_api_key: 
    file: ./run/secrets.d/cf_dns_api_key.txt
  tautulli_github_auth:
    file: ./run/secrets.d/tautulli_github_auth.txt
