  traefik:
    image: traefik
    container_name: traefik
    networks:
      - media_net
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080 # expose the dashboard only in traefik network 
    volumes:
      - "./apps/traefik/ssl-certs:/ssl-certs"
      - "./apps/traefik/etc/traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    environment:
      - CF_EMAIL_FILE = "run/secrets.d/cf_email"
      - CF_API_TOKEN_FILE = "run/secrets.d/cf_api_key"
      - DOMAIN =  ${DOMAIN:-example.com}
      - TZ =      ${TZ:-Etc/UTC}
      - PUID =    ${PUID:-1000}
      - PGID =    ${PGID:-1000}
      - HOST_IP = ${HOST_IP}
    secrets:
      - cf_email
      - cf_api_token
    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.traefik_https.rule=Host(`traefik.${DOMAIN}`)" # <== Setting the domain for the 
      - "traefik.http.routers.traefik_https.entrypoints=web,websecure"
      - "traefik.http.routers.traefik_https.service=traefik-service"
      - "traefik.http.services.traefik-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik_https.tls=true"
      - "traefik.http.routers.traefik_https.tls.certresolver=staging"
      - "traefik.http.routers.traefik_https.middlewares=basic-auth-global"
      - "traefik.http.middlewares.basic-auth-global.basicauth.usersfile=/etc/traefik/users"

secrets:
  cf_email:
    file: ./run/secrets.d/cf_email.txt
  cf_api_token: 
    file: ./run/secrets.d/cf_api_token.txt
